version: '2'
services:
  pinlinkfetcher:
    build:
      context: .
      dockerfile: Dockerfile.pinlinkfetcher
    image: pinlinkfetcher:latest
    container_name: pinlinkfetcher
    network_mode: host
    restart: always
    environment:
      CHROME_HEADLESS_HOST: "localhost"
      CHROME_HEADLESS_PORT: "9222"
