version: '2'
services:
  chrome-headless:
    image: knqz/chrome-headless:61.0.3114.2
    container_name: chrome-headless
    network_mode: host
    restart: always

  pinlinkfetcher:
    build:
      context: .
      dockerfile: Dockerfile.pinlinkfetcher
    image: pinlinkfetcher:latest
    container_name: pinlinkfetcher
    network_mode: host
    restart: always

  pindownloadr:
    build:
      context: .
      dockerfile: Dockerfile.pindownloadr2
    image: pindownloadr:latest
    container_name: pindownloadr
    network_mode: host
    volumes:
      - /tmp:/tmp

